spring.application.name=employee-service

server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/employee_db

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html