spring.application.name=employee-service

server.port=8082

# MongoDB
#spring.data.mongodb.uri=mongodb://localhost:27017/employee_db
spring.data.mongodb.uri=mongodb+srv://rajeevranjanprasad750:Ibm1234%40%23%24@auth-ms-db.vy28ujd.mongodb.net/emp_db?retryWrites=true&w=majority&appName=auth-ms-db

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Token
#jwt.secret=YourVeryLongSecretKeyThatMustBeAtLeast32CharactersLong123456
jwt.secret=YourVeryLongSecretKeyThatMustBeAtLeast32CharactersLong123456
jwt.expiration=86400000